// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLVg2eaP8m2fpUwIVxmPMJ1r5j7qikw0Y',
    appId: '1:644065683975:web:def2d8a20b28c7e79718a2',
    messagingSenderId: '644065683975',
    projectId: 'notificationfull-d0b73',
    authDomain: 'notificationfull-d0b73.firebaseapp.com',
    storageBucket: 'notificationfull-d0b73.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA11zVrsKwKAYicUJGkRLs074pVrhYd8J8',
    appId: '1:644065683975:android:bf2c0d74afb065cf9718a2',
    messagingSenderId: '644065683975',
    projectId: 'notificationfull-d0b73',
    storageBucket: 'notificationfull-d0b73.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVXi83fP9MlwAvs8ZUMIG-dS-CMaFg47g',
    appId: '1:644065683975:ios:0cddc01650ee2bbe9718a2',
    messagingSenderId: '644065683975',
    projectId: 'notificationfull-d0b73',
    storageBucket: 'notificationfull-d0b73.appspot.com',
    iosBundleId: 'com.example.pushnofull',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVXi83fP9MlwAvs8ZUMIG-dS-CMaFg47g',
    appId: '1:644065683975:ios:0cddc01650ee2bbe9718a2',
    messagingSenderId: '644065683975',
    projectId: 'notificationfull-d0b73',
    storageBucket: 'notificationfull-d0b73.appspot.com',
    iosBundleId: 'com.example.pushnofull',
  );
}
